name: Deploy to Render

on:
  push:
    branches:
      - tonco/integration-tests

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker-compose build

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST https://api.render.com/v1/services/${SERVICE_ID}/deploys \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -d '{}'
